# https://hub.docker.com/_/mongo
version: '3.8'

services:
    mongo-express:
      build: .
      restart: unless-stopped
      ports:
        - 8081:8081
      environment:
        CONFIG_MONGODB_USERNAME: accountAdmin01
        CONFIG_MONGODB_ADMINPASSWORD: shakiba2000
        DB_HOST : localhost
        PORT : 8081
        EXPIRE: 30


      depends_on:
        - mongodb


    mongodb:
      image: mongo
      restart: unless-stopped
#      command: mongod --auth
      ports:
        - 27017:27017
      volumes:
        - ./data:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: accountAdmin01
        MONGO_INITDB_ROOT_PASSWORD: shakiba2000
        MONGO_INITDB_DATABASE : notesDB
        MONGODB_DATA_DIR: /data/db
        MONDODB_LOG_DIR: /dev/null



